# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 41a709b8e92be0a12d7f22d28b78e2355efaa8b9a054bd01d9e9e249900e74c5413b8494dae7292c2298aa3271d44ac5bab04fd5d312aafbfd3c151f4e40f368

test:
  secret_key_base: 442ac9b309aabfef29ce26f09bd5b6603c9255f7643029fa70547260f6bb202055cdf48a86ae0af68e0a5eeb2e4698de54decf4950bc349e2218feb365af0ae2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
