# == Schema Information
#
# Table name: noticias
#
#  id                  :integer          not null, primary key
#  titulo              :string
#  descripcion         :text
#  estado_noticia      :string
#  created_at          :datetime         not null
#  updated_at          :datetime         not null
#  imagen_file_name    :string
#  imagen_content_type :string
#  imagen_file_size    :integer
#  imagen_updated_at   :datetime
#

require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

RSpec.describe NoticiasController, type: :controller do

  # This should return the minimal set of attributes required to create a valid
  # Noticia. As you add validations to Noticia, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # NoticiasController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET #index" do
    it "assigns all noticias as @noticias" do
      noticia = Noticia.create! valid_attributes
      get :index, {}, valid_session
      expect(assigns(:noticias)).to eq([noticia])
    end
  end

  describe "GET #show" do
    it "assigns the requested noticia as @noticia" do
      noticia = Noticia.create! valid_attributes
      get :show, {:id => noticia.to_param}, valid_session
      expect(assigns(:noticia)).to eq(noticia)
    end
  end

  describe "GET #new" do
    it "assigns a new noticia as @noticia" do
      get :new, {}, valid_session
      expect(assigns(:noticia)).to be_a_new(Noticia)
    end
  end

  describe "GET #edit" do
    it "assigns the requested noticia as @noticia" do
      noticia = Noticia.create! valid_attributes
      get :edit, {:id => noticia.to_param}, valid_session
      expect(assigns(:noticia)).to eq(noticia)
    end
  end

  describe "POST #create" do
    context "with valid params" do
      it "creates a new Noticia" do
        expect {
          post :create, {:noticia => valid_attributes}, valid_session
        }.to change(Noticia, :count).by(1)
      end

      it "assigns a newly created noticia as @noticia" do
        post :create, {:noticia => valid_attributes}, valid_session
        expect(assigns(:noticia)).to be_a(Noticia)
        expect(assigns(:noticia)).to be_persisted
      end

      it "redirects to the created noticia" do
        post :create, {:noticia => valid_attributes}, valid_session
        expect(response).to redirect_to(Noticia.last)
      end
    end

    context "with invalid params" do
      it "assigns a newly created but unsaved noticia as @noticia" do
        post :create, {:noticia => invalid_attributes}, valid_session
        expect(assigns(:noticia)).to be_a_new(Noticia)
      end

      it "re-renders the 'new' template" do
        post :create, {:noticia => invalid_attributes}, valid_session
        expect(response).to render_template("new")
      end
    end
  end

  describe "PUT #update" do
    context "with valid params" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested noticia" do
        noticia = Noticia.create! valid_attributes
        put :update, {:id => noticia.to_param, :noticia => new_attributes}, valid_session
        noticia.reload
        skip("Add assertions for updated state")
      end

      it "assigns the requested noticia as @noticia" do
        noticia = Noticia.create! valid_attributes
        put :update, {:id => noticia.to_param, :noticia => valid_attributes}, valid_session
        expect(assigns(:noticia)).to eq(noticia)
      end

      it "redirects to the noticia" do
        noticia = Noticia.create! valid_attributes
        put :update, {:id => noticia.to_param, :noticia => valid_attributes}, valid_session
        expect(response).to redirect_to(noticia)
      end
    end

    context "with invalid params" do
      it "assigns the noticia as @noticia" do
        noticia = Noticia.create! valid_attributes
        put :update, {:id => noticia.to_param, :noticia => invalid_attributes}, valid_session
        expect(assigns(:noticia)).to eq(noticia)
      end

      it "re-renders the 'edit' template" do
        noticia = Noticia.create! valid_attributes
        put :update, {:id => noticia.to_param, :noticia => invalid_attributes}, valid_session
        expect(response).to render_template("edit")
      end
    end
  end

  describe "DELETE #destroy" do
    it "destroys the requested noticia" do
      noticia = Noticia.create! valid_attributes
      expect {
        delete :destroy, {:id => noticia.to_param}, valid_session
      }.to change(Noticia, :count).by(-1)
    end

    it "redirects to the noticias list" do
      noticia = Noticia.create! valid_attributes
      delete :destroy, {:id => noticia.to_param}, valid_session
      expect(response).to redirect_to(noticias_url)
    end
  end

end
