# == Schema Information
#
# Table name: quienes_somos
#
#  id                   :integer          not null, primary key
#  mision               :text
#  vision               :text
#  politica_integral    :text
#  valores_corporativos :text
#  historia             :text
#  created_at           :datetime         not null
#  updated_at           :datetime         not null
#

require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

RSpec.describe QuienesSomosController, type: :controller do

  # This should return the minimal set of attributes required to create a valid
  # QuienSomos. As you add validations to QuienSomos, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # QuienesSomosController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET #index" do
    it "assigns all quienes_somos as @quienes_somos" do
      quien_somos = QuienSomos.create! valid_attributes
      get :index, {}, valid_session
      expect(assigns(:quienes_somos)).to eq([quien_somos])
    end
  end

  describe "GET #show" do
    it "assigns the requested quien_somos as @quien_somos" do
      quien_somos = QuienSomos.create! valid_attributes
      get :show, {:id => quien_somos.to_param}, valid_session
      expect(assigns(:quien_somos)).to eq(quien_somos)
    end
  end

  describe "GET #new" do
    it "assigns a new quien_somos as @quien_somos" do
      get :new, {}, valid_session
      expect(assigns(:quien_somos)).to be_a_new(QuienSomos)
    end
  end

  describe "GET #edit" do
    it "assigns the requested quien_somos as @quien_somos" do
      quien_somos = QuienSomos.create! valid_attributes
      get :edit, {:id => quien_somos.to_param}, valid_session
      expect(assigns(:quien_somos)).to eq(quien_somos)
    end
  end

  describe "POST #create" do
    context "with valid params" do
      it "creates a new QuienSomos" do
        expect {
          post :create, {:quien_somos => valid_attributes}, valid_session
        }.to change(QuienSomos, :count).by(1)
      end

      it "assigns a newly created quien_somos as @quien_somos" do
        post :create, {:quien_somos => valid_attributes}, valid_session
        expect(assigns(:quien_somos)).to be_a(QuienSomos)
        expect(assigns(:quien_somos)).to be_persisted
      end

      it "redirects to the created quien_somos" do
        post :create, {:quien_somos => valid_attributes}, valid_session
        expect(response).to redirect_to(QuienSomos.last)
      end
    end

    context "with invalid params" do
      it "assigns a newly created but unsaved quien_somos as @quien_somos" do
        post :create, {:quien_somos => invalid_attributes}, valid_session
        expect(assigns(:quien_somos)).to be_a_new(QuienSomos)
      end

      it "re-renders the 'new' template" do
        post :create, {:quien_somos => invalid_attributes}, valid_session
        expect(response).to render_template("new")
      end
    end
  end

  describe "PUT #update" do
    context "with valid params" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested quien_somos" do
        quien_somos = QuienSomos.create! valid_attributes
        put :update, {:id => quien_somos.to_param, :quien_somos => new_attributes}, valid_session
        quien_somos.reload
        skip("Add assertions for updated state")
      end

      it "assigns the requested quien_somos as @quien_somos" do
        quien_somos = QuienSomos.create! valid_attributes
        put :update, {:id => quien_somos.to_param, :quien_somos => valid_attributes}, valid_session
        expect(assigns(:quien_somos)).to eq(quien_somos)
      end

      it "redirects to the quien_somos" do
        quien_somos = QuienSomos.create! valid_attributes
        put :update, {:id => quien_somos.to_param, :quien_somos => valid_attributes}, valid_session
        expect(response).to redirect_to(quien_somos)
      end
    end

    context "with invalid params" do
      it "assigns the quien_somos as @quien_somos" do
        quien_somos = QuienSomos.create! valid_attributes
        put :update, {:id => quien_somos.to_param, :quien_somos => invalid_attributes}, valid_session
        expect(assigns(:quien_somos)).to eq(quien_somos)
      end

      it "re-renders the 'edit' template" do
        quien_somos = QuienSomos.create! valid_attributes
        put :update, {:id => quien_somos.to_param, :quien_somos => invalid_attributes}, valid_session
        expect(response).to render_template("edit")
      end
    end
  end

  describe "DELETE #destroy" do
    it "destroys the requested quien_somos" do
      quien_somos = QuienSomos.create! valid_attributes
      expect {
        delete :destroy, {:id => quien_somos.to_param}, valid_session
      }.to change(QuienSomos, :count).by(-1)
    end

    it "redirects to the quienes_somos list" do
      quien_somos = QuienSomos.create! valid_attributes
      delete :destroy, {:id => quien_somos.to_param}, valid_session
      expect(response).to redirect_to(quienes_somos_url)
    end
  end

end
